#FROM python:3.11-slim

#ORKDIR /app

#RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

#COPY requirements.txt /app/requirements.txt
#RUN pip install --no-cache-dir -r requirements.txt

#OPY ./app /app

#EXPOSE 8000
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

FROM python:3.11-slim

WORKDIR /app

# Install build tools + argon2 backend
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirement file from backend folder
COPY ./app/requirements.txt /app/app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r app/requirements.txt \
    && pip install --no-cache-dir argon2_cffi

# Copy backend source
COPY ./app /app/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
