name: CI Docker Build

on:
  push:
    branches: [ main, adolfo ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Run backend smoke test
        run: |
          docker compose up -d backend
          sleep 10
          docker exec swapstop-backend python -m compileall app
          docker compose down
